#!/bin/sh

DAEMON="dnsmasq"
PIDFILE="/var/run/$DAEMON.pid"

[ -f /etc/dnsmasq.conf ] || exit 0

case "$1" in
	start)
		printf "Starting dnsmasq: "
		if start-stop-daemon -S -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- --pid-file="$PIDFILE"; then
			echo "OK"
		else
			echo "FAIL"
		fi
		;;
	stop)
		printf "Stopping dnsmasq: "
		if start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON"; then
			echo "OK"
		else
			echo "FAIL"
		fi
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
